---
title: "PCS Simulations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggpubr)
library(plotly)
library(latex2exp)
library(R.utils)
library(kableExtra)
library(knitr)
library(DT)

source("functions/dgp_wrappers.R", chdir = T)
source("functions/method_wrappers.R", chdir = T)
source("functions/eval_library.R", chdir = T)
source("functions/plotting_wrappers.R", chdir = T)

library(pcs.sim.pkg)

```

```{r}
dgp <- create_dgp(linear_gaussian_dgp, n = 100, p_obs = 1, p_unobs = 1,
                  betas = 1, betas_unobs = 1, err_type = "gaussian")
z_test <- create_method(get_classical_pval, test_covar_index = 1)
pcs_test <- create_method(get_pcs_pval_mvols_gaussian, 
                          test_covar_index = 1, B = 10)
eval_indiv <- create_evaluator(eval_test)
eval_summary <- create_evaluator(eval_summary_test, alpha = 0.1)
power_plot <- create_plot(plotPower)#, rmd_options = list(height = 4))
pval_plot <- create_plot(plotPvalueStatistics, alpha = 0.05)

# create the experiment and add the dgp and method
experiment <- create_experiment(name = "PCS Simulation") %>%
  add_dgp(dgp, "Linear Gaussian") %>%
  add_method(z_test, "Z Test") %>%
  add_method(pcs_test, "PCS Test") %>%
  add_evaluator(eval_indiv, "Individual Metrics") %>%
  add_evaluator(eval_summary, "Summary Metrics") %>%
  add_plot(power_plot, "Power") %>%
  add_plot(pval_plot, "P-value Statistics")

future::plan(future::sequential)

# run sequentually
seq_start <- proc.time()
fit_results <- experiment$fit(n_reps = 1000, save = T)
eval_results <- experiment$evaluate(fit_results, save = T)
plot_results <- experiment$plot(fit_results, eval_results, save = T)
proc.time() - seq_start

vary_n <- experiment %>%
  add_vary_across(dgp = "Linear Gaussian",
                  param_name = "n", param_values = c(100, 200, 300))
fit_results <- experiment$fit(n_reps = 1000, save = T)
eval_results <- experiment$evaluate(fit_results, save = T)
plot_results <- experiment$plot(fit_results, eval_results, save = T)

vary_betas <- experiment %>%
  update_vary_across(dgp = "Linear Gaussian",
                     param_name = "betas", param_values = c(0.1, 1, 10))
fit_results <- experiment$fit(n_reps = 1000, save = T)
eval_results <- experiment$evaluate(fit_results, save = T)
plot_results <- experiment$plot(fit_results, eval_results, save = T)

vary_pcs <- experiment %>%
  remove_vary_across() %>%
  add_vary_across(method = "PCS Test",
                  param_name = "test_covar_index", param_values = c(1, 1))
fit_results <- experiment$fit(n_reps = 1000, save = T)
eval_results <- experiment$evaluate(fit_results, save = T)
plot_results <- experiment$plot(fit_results, eval_results, save = T)

# experiment$create_doc_template()

# generate rmd report
experiment$create_rmd()
# or alternatively,
# create_rmd(experiment)
# create_rmd(experiment_dirname = "results/PCS Simulation")

```


# Creating via children method

```{r}
dgp <- create_dgp(linear_gaussian_dgp, n = 100, p_obs = 1, p_unobs = 1,
                  betas = 1, betas_unobs = 1, err_type = "gaussian")
z_test <- create_method(get_classical_pval, test_covar_index = 1)
pcs_test <- create_method(get_pcs_pval_mvols_gaussian, 
                          test_covar_index = 1, B = 10)
eval_indiv <- create_evaluator(eval_test)
eval_summary <- create_evaluator(eval_summary_test, alpha = 0.1)
power_plot <- create_plot(plotPower)#, rmd_options = list(height = 4))
pval_plot <- create_plot(plotPvalueStatistics, alpha = 0.05)

# create the experiment and add the dgp and method
experiment <- create_experiment(n_reps = 1000, name = "PCS Simulation2") %>%
  add_dgp(dgp, "Linear Gaussian") %>%
  add_method(z_test, "Z Test") %>%
  add_method(pcs_test, "PCS Test") %>%
  add_evaluator(eval_indiv, "Individual Metrics") %>%
  add_evaluator(eval_summary, "Summary Metrics") %>%
  add_plot(power_plot, "Power") %>%
  add_plot(pval_plot, "P-value Statistics")

future::plan(future::sequential)

# run sequentually
seq_start <- proc.time()
# o1 <- experiment$fit(n_reps = 1000)
fit_results <- experiment$fit(n_reps = 1000, save = T)
eval_results <- experiment$evaluate(fit_results, save = T)
plot_results <- experiment$plot(fit_results, eval_results, save = T)
proc.time() - seq_start

save_dir <- experiment$get_save_dir()
vary_n <- create_experiment(clone_from = experiment, 
                            name = "Linear Gaussian - Vary n",
                            save_dir = experiment$save_dir) %>%
  add_vary_across(dgp = "Linear Gaussian", 
                  param_name = "n", param_values = c(100, 200, 300))
fit_results <- vary_n$fit(save = T)
eval_results <- vary_n$evaluate(fit_results, save = T)
plot_results <- vary_n$plot(fit_results, eval_results, save = T)

vary_betas <- create_experiment(n_reps = 1000, parent = experiment,
                                name = "Linear Gaussian - Vary betas",
                                save_dir = experiment$save_dir) %>%
  add_vary_across(dgp = "Linear Gaussian", 
                  param_name = "betas", param_values = c(0.1, 1, 10))
fit_results <- vary_betas$fit(n_reps = 1000, save = T)
eval_results <- vary_betas$evaluate(fit_results, save = T)
plot_results <- vary_betas$plot(fit_results, eval_results, save = T)

vary_pcs <- create_experiment(n_reps = 1000, parent = experiment,
                              name = "PCS Test - Vary test_covar_index",
                              save_dir = experiment$save_dir) %>%
  add_vary_across(method = "PCS Test", 
                  param_name = "test_covar_index", param_values = c(1, 1))
fit_results <- vary_pcs$fit(n_reps = 1000, save = T)
eval_results <- vary_pcs$evaluate(fit_results, save = T)
plot_results <- vary_pcs$plot(fit_results, eval_results, save = T)

experiment$create_rmd()

```

