---
title: "`r params$sim_name`"
author: "`r params$author`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
    - \usepackage{float}
    - \usepackage{amsmath}
    - \usepackage{gensymb}
output:
  rmdformats::material:
    fig_caption: true
css: css/general_rmd_theme_addons.css
params:
  author: 
    label: "Author:"
    value: ""
  sim_name:
    label: "Simulation Experiment Name:"
    value: ""
  sim_path:
    label: "Path to Simulation Experiment Folder:"
    value: ""
  eval_order:
    label: "Order of Evaluators:"
    value: NULL
  viz_order:
    label: "Order of Visualizers:"
    value: NULL
  verbose:
    label: "Verbose Level:"
    value: 2
---

```{r setup, include=FALSE}
options(width = 10000)
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.pos = "H",
  fig.height = 12,
  fig.width = 10
)

options(knitr.kable.NA = 'NA',
        dplyr.summarise.inform = FALSE)

# scrollable text output
local({
  hook_output <- knitr::knit_hooks$get('output')
  knitr::knit_hooks$set(output = function(x, options) {
    if (!is.null(options$max.height)) options$attr.output <- c(
      options$attr.output,
      sprintf('style="max-height: %s;"', options$max.height)
    )
    hook_output(x, options)
  })
})

chunk_idx <- 1
doc_dir <- file.path(params$sim_path, "docs")
```

```{r helper-funs}

#' Get order of objects to display
#'
#' @param obj_names Vector of all object names that need to be displayed.
#' @param obj_order Vector of object names in the desired appearance order.
#' @return Vector of object names in the order in which they will be displayed.
getObjOrder <- function(obj_names, obj_order = NULL) {
  if (is.null(obj_order)) {
    return(obj_names)
  } else {
    return(intersect(obj_order, obj_names))
  }
}

#' Get all experiments under a given directory name
#'
#' @param dir_name name of directory
#' @return list of named experiments
getDescendants <- function(dir_name) {
  experiments <- list()
  for (d in list.dirs(dir_name)) {
    if (file.exists(file.path(d, "experiment.rds"))) {
      if (identical(d, params$sim_path)) {
        exp_name <- "Base"
      } else {
        exp_name <- stringr::str_replace_all(
          stringr::str_remove(d, paste0(params$sim_path, "/")),
          "/", " - "
        )
      }
      experiments[[exp_name]] <- readRDS(file.path(d, "experiment.rds"))
    }
  }
  return(experiments)
}

#' Check if experiment exists
#'
#' @param dir_name name of directory or vector thereof
#' @param recursive logical; if TRUE, checks if experiment exists under the
#'   given directory(s); if FALSE, checks if any experiment exists under the
#'   directory(s) and its descendants
#' @return TRUE if experiment exists and FALSE otherwise
experimentExists <- function(dir_name, recursive = FALSE) {
  res <- purrr::map_lgl(dir_name,
                        function(d) {
                          if (!recursive) {
                            exp_fname <- file.path(d, "experiment.rds")
                            return(file.exists(exp_fname))
                          } else {
                            descendants <- getDescendants(d)
                            return(length(descendants) > 0)
                          }
                        })
  return(any(res))
}

#' Displays content for specified part of recipe
#'
#' @param field_name part of recipe to show; must be one of "dgp", "method",
#'   "evaluator", or "visualizer"
#' @return content for recipe
showRecipePart <- function(field_name = c("dgp", "method",
                                          "evaluator", "visualizer")) {

  field_name <- match.arg(field_name)
  func_name <- dplyr::case_when(field_name == "evaluator" ~ "eval",
                                field_name == "visualizer" ~ "viz",
                                TRUE ~ field_name)
  descendants <- getDescendants(dir_name = params$sim_path)
  objs <- purrr::map(descendants, ~.x[[paste0("get_", field_name, "s")]]())
  obj_names <- unique(purrr::reduce(sapply(objs, names), c))

  obj_header <- "<p style='font-weight: bold; font-size: 20px'> %s </p>"
  invis_header <- "\n\n### %s {.tabset .tabset-pills .tabset-fade .tabset-circle}\n\n"
  showtype_header <- "\n\n#### %s {.tabset .tabset-pills .tabset-fade .tabset-square}\n\n"
  exp_header <- "\n\n##### %s \n\n"

  if (all(sapply(objs, length) == 0)) {
    return(cat("N/A"))
  }

  for (idx in 1:length(obj_names)) {
    cat(sprintf(invis_header, ""))
    obj_name <- obj_names[idx]

    cat("<div class='panel panel-default padded-panel'>")
    cat(sprintf(obj_header, obj_name))

    cat(sprintf(showtype_header, fontawesome::fa("readme")))
    pasteMd(file.path(doc_dir, paste0(field_name, "s"),
                      paste0(obj_name, ".md")))

    cat(sprintf(showtype_header, fontawesome::fa("code")))
    keep_objs <- purrr::map(objs, obj_name)
    keep_objs[sapply(keep_objs, is.null)] <- NULL
    if (all(purrr::map_lgl(keep_objs,
                           ~isTRUE(check_equal(.x, keep_objs[[1]]))))) {
      obj <- keep_objs[[1]]
      cat("<b>Function</b>")
      subchunkify(obj[[paste0(func_name, "_fun")]],
                  chunk_idx, other_args = "max.height='200px'")
      chunk_idx <<- chunk_idx + 1
      cat("<b>Input Parameters</b>")
      subchunkify(obj[[paste0(func_name, "_params")]],
                  chunk_idx, other_args = "max.height='200px'")
      chunk_idx <<- chunk_idx + 1
    } else {
      for (exp in names(objs)) {
        obj <- objs[[exp]][[obj_name]]
        if (is.null(obj)) {
          next
        }
        cat(sprintf(exp_header, exp))
        cat("<b>Function</b>")
        subchunkify(obj[[paste0(func_name, "_fun")]],
                    chunk_idx, other_args = "max.height='200px'")
        chunk_idx <<- chunk_idx + 1
        cat("<b>Input Parameters</b>")
        subchunkify(obj[[paste0(func_name, "_params")]],
                    chunk_idx, other_args = "max.height='200px'")
        chunk_idx <<- chunk_idx + 1
      }
    }
    cat("</div>")
  }
}

#' Reads in file if it exists and returns NULL if the file does not exist
#'
#' @param filename name of .rds file to try reading in
#' @return output of filename.rds if the file exists and NULL otherwise
getResults <- function(filename) {
  if (file.exists(filename)) {
    results <- readRDS(filename)
  } else {
    results <- NULL
  }
  return(results)
}

#' Displays output (both from evaluate() and visualize()) from saved results under
#' a specified directory
#'
#' @param dir_name name of directory
#' @param depth integer; depth of directory from parent/base experiment's folder
#' @param base logical; whether or not this is a base experiment
#' @param show_header logical; whether or not to show section header
#' @param verbose integer; 0 = no messages; 1 = print out directory name only;
#'   2 = print out directory name and name of evaluators/visualizers
#' @return content results from evaluate() and visualize() from the experiment
showResults <- function(dir_name, depth, base = FALSE, show_header = TRUE,
                        verbose = 1) {
  if (verbose >= 1) {
    message(rep("*", depth), basename(dir_name))
  }

  if (depth == 1) {
    header_template <- "\n\n%s %s {.tabset .tabset-pills .tabset-fade}\n\n"
  } else {
    if (base | !experimentExists(dir_name)) {
      header_template <- "\n\n%s %s {.tabset .tabset-pills .tabset-fade .tabset-square}"
    } else {
      header_template <- "\n\n%s %s {.tabset .tabset-pills .tabset-fade .tabset-circle}"
    }
  }

  if (show_header) {
    cat(sprintf(header_template,
                paste(rep("#", depth), collapse = ""),
                basename(dir_name)))
  }

  if (base) {
    cat(paste0("\n\n",
               paste(rep("#", depth + 1), collapse = ""),
               " Base - ", basename(dir_name),
               " {.tabset .tabset-pills .tabset-fade .tabset-circle}\n\n"))
    depth <- depth + 1
  }

  showtype_template <- paste0(
    "\n\n", paste(rep("#", depth + 1), collapse = ""), " %s\n\n"
  )
  figname_template <- "<h3 style='font-weight: bold'> %s </h3>"
  invisible_header <- paste0(
    "\n\n", paste(rep("#", depth + 2), collapse = ""),
    " {.tabset .tabset-pills .tabset-fade .tabset-square}\n\n"
  )
  plt_template <- paste0(
    "\n\n", paste(rep("#", depth + 3), collapse = ""), " %s\n\n"
  )

  exp_fname <- file.path(dir_name, "experiment.rds")
  # fit_fname <- file.path(dir_name, "fit_results.rds")
  eval_fname <- file.path(dir_name, "eval_results.rds")
  viz_fname <- file.path(dir_name, "viz_results.rds")

  exp <- getResults(exp_fname)
  # fit_results <- getResults(fit_fname)
  eval_results <- getResults(eval_fname)
  viz_results <- getResults(viz_fname)

  if (!is.null(eval_results)) {
    cat(sprintf(showtype_template, fontawesome::fa("table")))
    eval_names <- getObjOrder(names(eval_results), params$eval_order)
    for (eval_name in eval_names) {
      if (verbose >= 2) {
        message(rep(" ", depth + 1), eval_name)
      }
      evaluator <- exp$get_evaluators()[[eval_name]]
      if (evaluator$show) {
        cat(sprintf(figname_template, eval_name))
        do.call(pretty_DT,
                c(list(eval_results[[eval_name]]), evaluator$rmd_options)) %>%
          subchunkify(i = chunk_idx)
        chunk_idx <<- chunk_idx + 1
      }
    }
  }

  if (!is.null(viz_results)) {
    cat(sprintf(showtype_template,
                fontawesome::fa("chart-bar")))
    viz_names <- getObjOrder(names(viz_results), params$viz_order)
    for (viz_name in viz_names) {
      if (verbose >= 2) {
        message(rep(" ", depth + 1), viz_name)
      }
      visualizer <- exp$get_visualizers()[[viz_name]]
      if (visualizer$show) {
        cat(invisible_header)
        cat(sprintf(figname_template, viz_name))
        plts <- viz_results[[viz_name]]
        if (!inherits(plts, "list")) {
          plts <- list(plt = plts)
        }
        if (is.null(names(plts))) {
          names(plts) <- 1:length(plts)
        }
        for (plt_name in names(plts)) {
          if (length(plts) != 1) {
            cat(sprintf(plt_template, plt_name))
          }
          plt <- plts[[plt_name]]
          subchunkify(plt, i = chunk_idx,
                      fig_height = visualizer$rmd_options$height,
                      fig_width = visualizer$rmd_options$width,
                      other_args = "out.width = '100%'")
          chunk_idx <<- chunk_idx + 1
        }
      }
    }
  }

  if (!is.null(exp)) {
    if ((length(exp$get_vary_across()$dgp) != 0) |
        (length(exp$get_vary_across()$method) != 0)) {
      cat(sprintf(showtype_template, fontawesome::fa("code")))
      cat("<b>Parameter Values</b>")
      subchunkify(exp$get_vary_across(),
                  chunk_idx, other_args = "max.height='200px'")
      chunk_idx <<- chunk_idx + 1
    }
  }
}

#' Displays output of experiment for all of its (saved) descendants
#'
#' @param dir_name name of parent experiment directory
#' @param depth placeholder for recursion; should not be messed with
#' @param ... other arguments to pass into showResults()
showDescendantResults <- function(dir_name, depth = 1, ...) {
  children <- list.dirs(dir_name, recursive = FALSE)
  if (length(children) == 0) {
    return()
  }
  for (child_idx in 1:length(children)) {
    child <- children[child_idx]
    if (!experimentExists(child, recursive = TRUE)) {
      next
    }
    if (experimentExists(child, recursive = FALSE) &
        (experimentExists(list.dirs(child, recursive = TRUE)[-1]) |
         (depth == 1))) {
      base <- TRUE
    } else {
      base <- FALSE
    }
    showResults(child, depth, base = base, ...)
    showDescendantResults(child, depth + 1, ...)
  }
}


```

# Simulation Experiment Recipe {.tabset .tabset-fade}

## Objectives {.panel .panel-default .padded-panel}

```{r objectives, results = "asis"}
pasteMd(file.path(doc_dir, "objectives.md"))
```

## Data Generation

```{r dgps, results = "asis"}
showRecipePart(field_name = "dgp")
```

## Methods and Evaluation

### Methods

```{r methods, results = "asis"}
showRecipePart(field_name = "method")
```

### Evaluation

```{r evaluators, results = "asis"}
showRecipePart(field_name = "evaluator")
```

## Visualizations

```{r visualizers, results = "asis"}
showRecipePart(field_name = "visualizer")
```



```{r res, results = "asis"}

# show results
if (experimentExists(params$sim_path)) {
  cat(sprintf("\n\n# Base %s \n\n", params$sim_name))
  cat("\n\n## {.tabset .tabset-pills .tabset-fade .tabset-circle}\n\n")
  message(sprintf("Creating R Markdown report for %s...", params$sim_name))
  showResults(params$sim_path, depth = 2, base = FALSE, show_header = FALSE,
              verbose = 0)
}

showDescendantResults(params$sim_path, verbose = params$verbose)

```
